//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartoder
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string CreatedDate { get; set; }
        public string Address { get; set; }
        public string Payment { get; set; }
        public string Total { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
